/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadPanel: typeof import('./src/components/ImgGet/DownloadPanel.vue')['default']
    E_Add: typeof import('./src/components/Nodes/e_Add.vue')['default']
    E_FlieUpload: typeof import('./src/components/Nodes/e_FlieUpload.vue')['default']
    E_Output: typeof import('./src/components/Nodes/e_Output.vue')['default']
    E_Predict: typeof import('./src/components/Nodes/e_Predict.vue')['default']
    E_Start: typeof import('./src/components/Nodes/e_Start.vue')['default']
    E_Sub: typeof import('./src/components/Nodes/e_Sub.vue')['default']
    E_ViewImg: typeof import('./src/components/Nodes/e_ViewImg.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FormComponent: typeof import('./src/components/ImgGet/FormComponent.vue')['default']
    InputNode: typeof import('./src/components/Nodes/InputNode.vue')['default']
    MainGraph: typeof import('./src/components/MainGraph.vue')['default']
    MapComponent: typeof import('./src/components/ImgGet/MapComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NodePanel: typeof import('./src/components/NodePanel.vue')['default']
    OutputNode: typeof import('./src/components/Nodes/OutputNode.vue')['default']
    ResultsList: typeof import('./src/components/ImgGet/ResultsList.vue')['default']
    RightPanel: typeof import('./src/components/ImgGet/RightPanel.vue')['default']
    RightSidebar: typeof import('./src/components/ImgGet/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Step1: typeof import('./src/components/ImgGet/Step1.vue')['default']
    Step2: typeof import('./src/components/ImgGet/Step2.vue')['default']
    VisualParams: typeof import('./src/components/ImgGet/VisualParams.vue')['default']
    WorkflowNavbar: typeof import('./src/components/WorkflowNavbar.vue')['default']
  }
}
